# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:50
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
