# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171018_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='/static/img/f4.png', upload_to='img'),
        ),
    ]
